(defun search (N Li)
   (cond ((eq Li nil) "Элемент не найден.")
      ((eq (car Li) N) "Элемент найден.")
      (T (search N (CDR Li)))
   )
)
(defun input ()
    (print "Исходный список:") (print Li)
    (print "Введите элемент для поиска:") (set 'N (read))
    (print "Результат поиска:") (search N Li)
)
(set 'Li '(15 3 12 67 0 33 21 11))
(input)